apiVersion: v1
kind: Service
metadata:
  name: latexgrambot
  namespace: latexgrambot
  labels:
    app.kubernetes.io/name: latexgrambot
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: latexgrambot
  ports:
    - name: http
      port: 8080
      targetPort: http
